name: Extract RootFS from Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "version.txt"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build . -t arch:$(cat version.txt)

      - name: Extract RootFS
        run: |
          docker create --name arch arch:$(cat version.txt)
          docker export -o rootfs.tar arch
          gzip rootfs.tar
          docker rm -f arch

      - name: Upload RootFS
        uses: actions/upload-artifact@v3
        with:
          name: rootfs.tar.gz
          path: rootfs.tar.gz
